# top level stuff you probably don't need to touch
safe: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
feed:
  path: atom.xml
exclude:
  - CNAME
  - README.md
  - CONTRIBUTING.md
  - Gemfile*
#excerpt_separator: "<!--more-->"
permalink: "/notes/:title"
defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "page"

# edit here to achieve your personal greatness
url: "https://wcoder.github.io" # the base hostname & protocol for your site
enforce_ssl: "wcoder.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
title: "ТехноБлог Пакало Евгения"
shortTitle: "ТехноБлог"
description: "Еще один техноблог, пишу о том что интересно."
author: "Евгений Пакало"
twitter_username: "evgeniypakalo"
github_username:  "wcoder"