# Site Info
name: "ТехноБлог Пакало Евгения" # for feed
title: "ТехноБлог Пакало Евгения"
shortTitle: "ТехноБлог"
description: "Еще один техноблог, пишу о том что интересно."

# Author Info
author: "Евгений Пакало"
twitter_username: "evgeniypakalo"
github_username:  "wcoder"

# Site Settings
url: "https://wcoder.github.io" # the base hostname & protocol for your site
enforce_ssl: "wcoder.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/notes/:title"
timezone: "Europe/Minsk"
paginate: 10

# Site Build
# safe: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
feed:
  path: atom.xml
exclude:
  - CNAME
  - README.md
  - CONTRIBUTING.md
  - Gemfile*
  - run_local.bat
#excerpt_separator: "<!--more-->"

# Other Params
defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "page"
      optimize: true
