# top level stuff you probably don't need to touch
safe: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
feed:
  path: atom.xml
exclude:
  - CNAME
  - README.md
  - CONTRIBUTING.md
  - Gemfile*
#excerpt_separator: "<!--more-->"
permalink: "/:title.html"
defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "page"

# edit here to achieve your personal greatness
url: "http://wcoder.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
title: "ТехноБлог: Евгений Пакало"
shortTitle: "ТехноБлог"
description: "Еще один техноблог, пишу о том что интересно."
author: "Евгений Пакало"
email: "evgeniy.pakalo@gmail.com"
twitter_username: "evgeniypakalo"
github_username:  "wcoder"