# top level stuff you probably don't need to touch
safe: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
feed:
  path: atom.xml
exclude:
  - CNAME
  - README.md
  - CONTRIBUTING.md
  - Gemfile*
#excerpt_separator: "<!--more-->"

# edit here to achieve your personal greatness
url: "http://wcoder.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
title: Personal blog
author: Yauheni Pakala
email: evgeniy.pakalo@gmail.com
description: "Personal blog and resume"
twitter_username: evgeniypakalo
github_username:  wcoder